sudo: required
dist: trusty
language: node_js
before_install:
- sudo dpkg --add-architecture i386
- sudo apt-get update
- sudo apt-get install -y wine

install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
node_js:
- '5'
cache:
  directories:
    - node_modules
script: npm run travis-test
