language: node_js
before_install:
- sudo dpkg --add-architecture i386
- sudo apt-get update
- sudo apt-get install -y -qq wine

install:
- yarn install
before_script:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- sleep 3
node_js:
- '5'
- '6'
- '7'
- '8'
script: npm run travis-test
